name: CMake

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - "docs/**"
  #pull_request:
  #  branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: ./set_prerequisites.sh

    - name: Configure CMake
      run: ./init.sh "${{ env.BUILD_TYPE }}"
    - name: Build
      run: ./mk.sh "${{ env.BUILD_TYPE }}"
    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute CMake BuiltTest test
    #  run: ctest -C ${{env.BUILD_TYPE}} -R BuildTest
    - name: Make Package
      run: ./makePackage.sh
       
    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
          name: pipedal-deb-${{ matrix.os }}
          path: build/*.deb
          retention-days: 5

    - name: Install to staging
      run: DESTDIR=${{ github.workspace }}/staging cmake --install build

    - name: Upload portable build
      uses: actions/upload-artifact@v4
      with:
          name: pipedal-portable-${{ matrix.os }}
          path: staging/**
          retention-days: 5
             
