name: CMake

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - "docs/**"
  #pull_request:
  #  branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential g++ git \
          nodejs npm curl
        sudo apt-get install -y liblilv-dev libboost-dev libsystemd-dev \
          catch libasound2-dev uuid-dev authbind libavahi-client-dev \
          libnm-dev libicu-dev libsdbus-c++-dev libzip-dev google-perftools \
          libgoogle-perftools-dev libpipewire-0.3-dev libbz2-dev \
          libssl-dev librsvg2-dev
        git submodule update --init --recursive
        ./react-config

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}
    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute CMake BuiltTest test
    #  run: ctest -C ${{env.BUILD_TYPE}} -R BuildTest
    - name: Make Package
      run: ./makePackage.sh
       
    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
          name: pipedal-deb-${{ matrix.os }}
          path: build/*.deb
          retention-days: 5

    - name: Upload portable build
      uses: actions/upload-artifact@v4
      with:
          name: pipedal-portable-${{ matrix.os }}
          path: |
              build/**
              !build/**/*.o
          retention-days: 5
             
